### ISSUE TITLE
20240128 해야 할 일들

### ISSUE THREAD

**Issue by yongseung-song** [yeolsss/nbc-nep#79]
# Todos
## 스크럼보드
- [ ] 카테고리 Delete 기능
- [ ] 카테고리 DnD 적용
- [ ] 카테고리 
## 완성도 높이기
- [ ] skeleton ui 만들기
- [ ] toastify 디자인 프로젝트 컨셉과 맞추기 : 위치, 색, 크기 등... -> git 아바타 넣으면 어떨까
- [ ] joyride 메시지 디자인 프로젝트 컨셉과 맞추기
